I'm trying to use PyCognito (AWS Cognito) to authenticate a user and an attached identity pool authenticated role to give permissions to the user to query an AppSync GraphQL endpoint but I'm getting a 401 Client Error: Unauthorized for url . Minimal Reproducible Example: raises the following exception: When I perform an sts.get_caller_identity() with the logged in credentials, I get the expected authenticated role from IAM. I have also added the following inline policy on the above authRole to try an blanket solve the permissions issue to no avail. I originally tried using this as a guide but didn't see anyone else here run into this 401 issue. How to send a GraphQL query to AppSync from python?