For the last 24 hours or so I'm seeing the below error messages when I try to install either of sexpdata 1.0.1 or segno 1.5.3 in python. I should perhaps note that these installs usually happen via github code runners (automated tests), which is what alerted me to the issue.  I can reproduce locally. My requirements.txt hasn't changed in many weeks and no substantive changes for even longer.  Climbing back up the commit tree doesn't change the error.  So I suspect the problem isn't in my code, but I also am not sure where the problem might lie, as sexpdata hasn't changed since June, according to its github repo . Any pointers what might be happening or what to look at? This was caused by the release of setuptools 69.0.0 on Nov 20, 2023, which has a list of deprecations and removals . The setup files (e.g. pyproject.toml ) of sexpdata 1.0.1 or segno 1.5.3 must have some things that do not comply with the latest rules. A simple fix is to change requires = ["setuptools>=61.0"] to requires = ["setuptools==68.2.2"] in the pyproject.toml file of sexpdata 1.0.1 , then the package should be able to be installed again. A permanent fix should update the setup files to make them comply with the rules. pyproject.toml