I am encountering an issue with my AWS Lambda function with runtime Python 3.9. The function uses Spacy (version 3.7.2) and is set up as a layer in AWS Lambda. During execution, I'm facing the following error. I've already attempted the following troubleshooting steps: Updated Spacy to the latest version using pip install --upgrade spacy . Disabled GPU support for Thinc in the Lambda function code using import thinc; thinc.require_gpu(False) . Despite these efforts, the issue persists. I suspect it might be related to the Lambda environment or the way dependencies are packaged. Here are some specific questions I have: Is there a known compatibility issue between Spacy 3.7.1 and Python 3.9 in AWS Lambda? Are there specific configurations or dependencies that need to be addressed for Spacy in the AWS Lambda environment? Could the "Unknown application error" be a result of the AttributeError related to os.add_dll_directory ? How to resolve this issue? If there are specific Lambda configurations or Spacy settings that need attention, please provide guidance.